using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using GTToolsSharp.Encryption;

namespace GTToolsSharp
{
    public static class KeysetStore
    {
        /// <summary>
        /// Used for contents decryption of all salsa encrypted related contents
        /// </summary>
        public static string GT5P_TVBASEKEY = "z+GpfENhXfpTo/CJ9UjbgX0H9siurJ8PAe0/mm1MOBc=";

        /// <summary>
        /// Used for menudb decryption (Salsa) - boot/boot_functions.ad
        /// </summary>
        public static string MENUDB_KEY = "81CE293873B342F4C96E850C977CBF7F9DF674DAC007CA1951B821509F3ADFA4";

        /// <summary>
        /// Used for specdb decryption (Salsa) - main/SpecDatabaseUtil.ad
        /// </summary>
        public static string SPECDB_KEY = "2D9EE83E63120EB25DF4981EE73C3BE194D0F059DE50C8D4FCB66C10D3EDC549";

        /// <summary>
        /// Used for caption db decryption (Salsa) - main/util/CaptionUtil.ad
        /// </summary>
        public static string CAPTIONDB_KEY = "76E3E647D7E41530C7E171BB558E78EDDC4FA9858D5F7B1E48446DE6EC58220101";

        /// <summary>
        /// Default generated by default
        /// </summary>
        public static readonly Keyset Keyset_DEFAULT = new Keyset("PFS_DEFAULT", "PDIPFSDEFAULT", new Key(0x04C11DB7, 0x04C11DB7, 0x04C11DB7, 0x04C11DB7));

        public static readonly Keyset Keyset_GT5P_JP_DEMO = new Keyset("GT5P_JP_DEMO", "PDIPFS-071020-02", default, new BufferDecryptManager
        {
            Keys = new()
            {
                { "car/lod/00030131", "SoyoGvyMYKCCjcYBCI8rY3GMy9eQlvy3KpEfuL2qZE4oAo5c" },
                { "car/menu/00030131", "SoyoGvyMYKCCjcYBCI8rY3GMy9eQlvy3KpEfuL2qZE6GuajW" },
                { "car/interior/00030131", "SoyoGvyMYKCCjcYBCI8rY3GMy9eQlvy3KpEfuL2qZE5JUizQ" },
                { "car/meter/00030131", "SoyoGvyMYKCCjcYBCI8rY3GMy9eQlvy3KpEfuL2qZE5iDFjf" },
                { "piece/car_thumb_M/gtr_07_01.img", "cjg1NDJzZDVmNGgyNXM0cnQ2eTJkcjg0Z3pkZmJ3ZmEtdwwS" },

                { "car/lod/00200032", "KeaQvtvmSURh566l5+kUB1DmtHtv8OVbCesIXJ0ETPI1QYGR" },
                { "car/menu/00200032", "KeaQvtvmSURh566l5+kUB1DmtHtv8OVbCesIXJ0ETPJS5l7P" },
                { "car/interior/00200032", "KeaQvtvmSURh566l5+kUB1DmtHtv8OVbCesIXJ0ETPKP9PTn" },
                { "piece/car_thumb_M/impreza_wrx_sti_07_03.img", "cTM0NWgzNTZ5djJoZzRmMTIzNDQ1NjQ1ajZqMjRoNWY4Rqik" },
            }
        });


        public static readonly Keyset Keyset_GT5P_JP = new Keyset("GT5P_JP", "PDIPFS-071201-11", new Key(0x04C11DB7, 0x04C11DB7, 0x04C11DB7, 0x04C11DB7));
        public static readonly Keyset Keyset_GT5P_SPEC2_US_PSN = new Keyset("GT5P_SPEC2_US_PSN", "SONORA-550937027", new Key(0xFD7F0A4B, 0x6DE31FCD, 0xB5B14A50, 0x2F174A36));
        public static readonly Keyset Keyset_GT5P_US_SPEC3 = new Keyset("GT5P_US_SPEC_III", "SONORA-550937027", new Key(0x4B0A7FFD, 0xCD1FE36D, 0x504AB1B5, 0x364A172F));
        public static readonly Keyset Keyset_GT5P_EU_SPEC3 = new Keyset("GT5P_EU_SPEC_III", "TOTTORI-562314254", new Key(0x5F29A71B, 0xA80945CF, 0xBECCA74F, 0x07C9800F));
        public static readonly Keyset Keyset_GT5P_CITROEN = new Keyset("GT5P_CITROEN", "KARAKUM-176730298", new Key(0x995515F1, 0xC7BA38EF, 0xA9837BE5, 0x60C4925F));
        public static readonly Keyset Keyset_GT5_TT_HK = new Keyset("GT5_TIME_TRIAL_CHALLENGE_HK", "ORDOS-29082919", new Key(0x33B41763, 0xB737084B, 0xD039E95F, 0xA42AF29B));
        public static readonly Keyset Keyset_GT5_TT_US = new Keyset("GT5_TIME_TRIAL_CHALLENG_US", "CARCROSS-85963023", new Key(0x7C90C351, 0x53D1057D, 0x358FA239, 0xF50932BF));
        public static readonly Keyset Keyset_GT5_TT_EU = new Keyset("GT5_TIME_TRIAL_CHALLENG_EU", "PISCINAS-77828733", new Key(0xDC110915, 0xAC7D03BD, 0xA694AF0D, 0x91E83CF1));
        public static readonly Keyset Keyset_GT5_KIOSK_DEMO = new Keyset("GT5_KIOSK_DEMO", "ARABIAN-312107402", new Key(0x3036F45D, 0xD134AB3F, 0x859A665B, 0x16F82F9D));
        public static readonly Keyset Keyset_GT5_EU = new Keyset("GT5_EU", "KALAHARI-37863889", new Key(0x2DEE26A7, 0x412D99F5, 0x883C94E9, 0x0F1A7069));
        public static readonly Keyset Keyset_GT5_US = new Keyset("GT5_US", "PATAGONIAN-22798263", new Key(0x5A1A59E5, 0x4D3546AB, 0xF30AF68B, 0x89F08D0D));
        public static readonly Keyset Keyset_GT5_JP = new Keyset("GT5_JP", "SAHARA-568201135", new Key(0xD770A27B, 0x2114AABD, 0xDD8C423D, 0x54690651));
        public static readonly Keyset Keyset_GT5_ASIA = new Keyset("GT5_ASIA", "TAKLAMAKAN-63706075", new Key(0x93783D89, 0x33D56FB5, 0xE7701B43, 0x6032AD93));
        public static readonly Keyset Keyset_GTAC_2012_EU = new Keyset("GT_ACADEMY_2012_EU", "GREATBASIN-579805832", new Key(0xE631DC25, 0x82C2998F, 0x4F875673, 0xBD641F33));
        public static readonly Keyset Keyset_GTAC_2012_US = new Keyset("GT_ACADEMY_2012_US", "CHIHUAHUAN-638729911", new Key(0x8128DD09, 0xA82AB067, 0x49DBA01F, 0x499939D3));
        public static readonly Keyset Keyset_GTAC_2012_ASIA = new Keyset("GT_ACADEMY_2012_ASIA", "GREATSANDY-774795678", new Key(0x95878E3F, 0xC58426A1, 0x72E21421, 0x1D3CC8FB));
        public static readonly Keyset Keyset_GTA2013 = new Keyset("GT6_ACADEMY_2013", "CHOLISTAN-901501638", new Key(0x98D2BDC1, 0x0968F1C5, 0xC857640B, 0xAEB52EF5));
        public static readonly Keyset Keyset_GT6 = new Keyset("GT6", "PISCINAS-323419048", new Key(0xAA1B6A59, 0xE70B6FB3, 0x62DC6095, 0x6A594A25));

        public static readonly Keyset Keyset_GTSPORT_BETA = new Keyset("GTSPORT", "KYZYLKUM-873068469", new Key(0x04C11DB7, 0x04C11DB7, 0x04C11DB7, 0x04C11DB7));
        public static readonly Keyset Keyset_GTSPORT = new Keyset("GTSPORT", "KYZYLKUM-873068469", new Key(0xC9DA80A5, 0x050DA9A1, 0x9EB1FE65, 0xB651F2FB));

        public static readonly Keyset[] Default_Keysets =
        {
            KeysetStore.Keyset_GT5P_JP_DEMO,

            KeysetStore.Keyset_DEFAULT,

            KeysetStore.Keyset_GT5P_SPEC2_US_PSN,
            KeysetStore.Keyset_GT5P_US_SPEC3,
            KeysetStore.Keyset_GT5P_EU_SPEC3,

            KeysetStore.Keyset_GT5P_CITROEN,

            KeysetStore.Keyset_GT5_TT_HK,
            KeysetStore.Keyset_GT5_TT_US,
            KeysetStore.Keyset_GT5_TT_EU,

            KeysetStore.Keyset_GT5_KIOSK_DEMO,

            KeysetStore.Keyset_GT5_EU,
            KeysetStore.Keyset_GT5_US,
            KeysetStore.Keyset_GT5_JP,
            KeysetStore.Keyset_GT5_ASIA,

            KeysetStore.Keyset_GTAC_2012_EU,
            KeysetStore.Keyset_GTAC_2012_US,
            KeysetStore.Keyset_GTAC_2012_ASIA,

            KeysetStore.Keyset_GTA2013,
            KeysetStore.Keyset_GT6,

            KeysetStore.Keyset_GTSPORT_BETA,
            KeysetStore.Keyset_GTSPORT,
        };

        public static readonly byte[] GT7_Index_Key = new byte[]
        {
            0xFB, 0x3E, 0xC1, 0x2D, 0x88, 0x35, 0x2C, 0x39, 0xF1, 0x66, 0x3E, 0xE2, 0x04, 0x04, 0xCB, 0x8C,
            0x1D, 0x47, 0xFE, 0xF2, 0x72, 0x3B, 0x13, 0x46, 0xF7, 0xD3, 0x7E, 0x1B, 0xBD, 0xC4, 0x5F, 0xA6
        };

        public static readonly byte[] GT7_Volume_Data_Key = new byte[]
        {
            0x61, 0x3E, 0xD4, 0x4E, 0xB7, 0x1D, 0xD6, 0x16, 0x9C, 0xCA, 0xA0, 0x06, 0x6D, 0x29, 0x02, 0xB8,
            0x90, 0xC0, 0x28, 0xA3, 0xC5, 0x9A, 0x98, 0x66, 0x24, 0xDD, 0xAD, 0x80, 0xFB, 0xF3, 0x04, 0x9B
        };

        public static readonly byte[] GT7_Index_IV = new byte[]
        {
            0x09, 0x21, 0xE1, 0xC5, 0x58, 0x1F, 0xAB, 0x35, 0x00, 0x00, 0x00, 0x00,
        };
    }
}
